import {
  WalletDisconnectButton,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import type { NextPage } from "next";
import Head from "next/head";
import Box from "@mui/material/Box";
import TransferPopUp from "../components/TransferPopUp";
import type { Theme, SxProps } from "@mui/material";

const styles: { [key: string]: SxProps<Theme> } = {
  pageContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
  },
  buttons: {
    display: "flex",
    gap: 2,
    alignItems: "center",
    justifyContent: "center",
    mb: 2,
  },
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={styles.pageContainer}>
        <h2>Transfer dapp practice</h2>
        <Box sx={styles.buttons}>
          <WalletMultiButton />
          <WalletDisconnectButton />
        </Box>
        <Box>
          <TransferPopUp />
        </Box>
      </Box>
    </div>
  );
};

export default Home;
